name: 'Install CoAPP tools'
description: 'Install CoAPP powershell tools.'
branding:
  icon: 'archive'
  color: 'purple'
runs:
  using: "composite"
  steps:
    - name: download CoAPP tools installer
      run: (new-object net.webclient).DownloadFile('http://coapp.org/files/CoApp.Tools.Powershell.msi', 'C:\CoApp.Tools.Powershell.msi')
      shell: powershell
    - name: install CoAPP tools
      run: Start-Process -FilePath msiexec -ArgumentList /i, 'C:\CoApp.Tools.Powershell.msi', /quiet -Wait
      shell: powershell
    - name: add CoAPP path to module lookup paths
      uses: myci-actions/append-to-path-windows@master
      with:
        path: C:\Program Files (x86)\Outercurve Foundation\Modules
        env-var: PSModulePath
    - name: import CoAPP module
      run: Import-Module CoApp
      shell: powershell
