name: 'Install CoAPP tools'
description: 'Install CoAPP powershell tools.'
branding:
  icon: 'archive'
  color: 'purple'
runs:
  using: "composite"
  steps:
    - name: download CoAPP tools installer
      run: |
        # (new-object net.webclient).DownloadFile('http://coapp.org/files/CoApp.Tools.Powershell.msi', 'C:\CoApp.Tools.Powershell.msi')
        (new-object net.webclient).DownloadFile('http://gagis.hopto.org/CoApp.Tools.Powershell.msi', 'C:\CoApp.Tools.Powershell.msi')
      shell: powershell
    - name: install CoAPP tools
      run: Start-Process -FilePath msiexec -ArgumentList /i, 'C:\CoApp.Tools.Powershell.msi', /quiet -Wait
      shell: powershell
    - name: add CoAPP path to module lookup paths using environment files to make the change permanent
      run: echo "PSModulePath=$env:PSModulePath;C:\Program Files (x86)\Outercurve Foundation\Modules" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
      shell: powershell
    - name: import CoAPP module
      run: Import-Module CoApp
      shell: powershell
